SUB = {}

SUB["japan"] = {'arborio rice': ['sushi rice'],
 'basmati': ['sushi rice'],
 'biangbiang noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'black rice': ['sushi rice'],
 'brown rice': ['sushi rice'],
 'cellophane noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'chinkiang pot cover noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'cumian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'cup noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'daoxiao noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'dragon beard noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fettucine': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fideo': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fried noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'frozen noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'henan braised noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'hot dry noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'instant noodle': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'jasmine rice': ['sushi rice'],
 'jook-sing noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'kaomianjin': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lai fun': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lamian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lasagne': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'liangpi': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'macaroni': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'matta rice': ['sushi rice'],
 'migan': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'misua': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mixian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mohnnudel': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mung bean sheets': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'oil noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'paomo': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'parboiled rice': ['sushi rice'],
 'penne': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'ravioli': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rice': ['sushi rice'],
 'rice noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rice vermicelli': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rigatoni': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'saang mein': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'schupfnudel': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'shahe fen': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'shrimp roe noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'silver needle noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'spaghetti': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'white rice': ['sushi rice'],
 'wild rice': ['sushi rice'],
 'yi mein': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'youmian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba']}

SUB["mexico"] = {}

