SUB = {}

SUB["to_vegetarian"] = {'anchovy': ['tofu', 'tempeh'],
 'bacon': ['impossible burger', 'plant-based red meat'],
 'bass': ['tofu', 'tempeh'],
 'beef': ['impossible burger', 'plant-based red meat'],
 'bison': ['impossible burger', 'plant-based red meat'],
 'catfish': ['tofu', 'tempeh'],
 'chicken': ['tofu', 'tempeh'],
 'clam': ['tofu', 'tempeh'],
 'cod': ['tofu', 'tempeh'],
 'cow milk': ['macadamia nut milk', 'coconut milk', 'soy milk', 'rice milk', 'cashew milk', 'almond milk'],
 'crab': ['tofu', 'tempeh'],
 'dove': ['tofu', 'tempeh'],
 'duck': ['tofu', 'tempeh'],
 'eel': ['tofu', 'tempeh'],
 'fish': ['tofu', 'tempeh'],
 'goat milk': ['macadamia nut milk', 'coconut milk', 'soy milk', 'rice milk', 'cashew milk', 'almond milk'],
 'goose': ['tofu', 'tempeh'],
 'grouse': ['tofu', 'tempeh'],
 'guineafowl': ['tofu', 'tempeh'],
 'halibut': ['tofu', 'tempeh'],
 'ham': ['impossible burger', 'plant-based red meat'],
 'lamb': ['impossible burger', 'plant-based red meat'],
 'lard': ['butter', 'goat butter'],
 'lobster': ['tofu', 'tempeh'],
 'mussel': ['tofu', 'tempeh'],
 'oyster': ['tofu', 'tempeh'],
 'partridge': ['tofu', 'tempeh'],
 'pheasant': ['tofu', 'tempeh'],
 'pigeon': ['tofu', 'tempeh'],
 'pork': ['impossible burger', 'plant-based red meat'],
 'prawn ': ['tofu', 'tempeh'],
 'quail': ['tofu', 'tempeh'],
 'salmon': ['tofu', 'tempeh'],
 'sausage': ['impossible burger', 'plant-based red meat'],
 'scallop': ['tofu', 'tempeh'],
 'shrimp': ['tofu', 'tempeh'],
 'steak': ['impossible burger', 'plant-based red meat'],
 'tilapia': ['tofu', 'tempeh'],
 'tuna': ['tofu', 'tempeh'],
 'turkey': ['tofu', 'tempeh'],
 'veal': ['impossible burger', 'plant-based red meat'],
 'venison': ['impossible burger', 'plant-based red meat']}

SUB["to_non_vegetarian"] = {'adzuki bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'almond milk': ['cow milk', 'goat milk'],
 'black bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'black turtle bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'butter': ['lard'],
 'cashew milk': ['cow milk', 'goat milk'],
 'chickpea': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'coconut milk': ['cow milk', 'goat milk'],
 'cowpeas': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'edamame': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'goat butter': ['lard'],
 'impossible burger': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'kidney bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'lentil': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'macadamia nut milk': ['cow milk', 'goat milk'],
 'mung bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'navy bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'pea': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'pinto bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'plant-based red meat': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'rice milk': ['cow milk', 'goat milk'],
 'small white bean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'soy milk': ['cow milk', 'goat milk'],
 'soybean': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'split pea': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'tempeh': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge'],
 'tofu': ['turkey', 'chicken', 'quail', 'goose', 'duck', 'pheasant', 'pigeon', 'dove', 'grouse', 'guineafowl', 'partridge']}

SUB["to_healthy"] = {'Froot Loops': ['Cheerios'],
 'Lucky Charms': ['Cheerios'],
 'bacon': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'beef': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'bison': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'canadian white': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'ciabatta': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'cuban bread': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'dampfnudel': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'ham': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'hardebrood': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'lamb': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'milk bread': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'milk loaf': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'milk roll': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'mollette': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'pane ticinese': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'piadina': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'pork': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'sausage': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'shoti': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'steak': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'texas toast': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread'],
 'veal': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'venison': ['fish', 'prawn ', 'crab', 'lobster', 'mussel', 'oyster', 'scallop', 'clam', 'bass', 'cod', 'catfish', 'tilapia', 'anchovy', 'tuna', 'salmon', 'eel', 'halibut', 'shrimp'],
 'zopf': ['whole grain bread', 'wheat bread', 'whole wheat bread', 'multigrain bread']}

SUB["to_unhealthy"] = {'Cheerios': ['Lucky Charms', 'Froot Loops'],
 'anchovy': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'bass': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'catfish': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'chicken': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'clam': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'cod': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'crab': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'dove': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'duck': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'eel': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'fish': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'goose': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'grouse': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'guineafowl': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'halibut': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'lobster': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'multigrain bread': ['canadian white', 'ciabatta', 'cuban bread', 'dampfnudel', 'hardebrood', 'mollette', 'milk loaf', 'milk bread', 'milk roll', 'pane ticinese', 'piadina', 'shoti', 'texas toast', 'zopf'],
 'mussel': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'oyster': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'partridge': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'pheasant': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'pigeon': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'prawn ': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'quail': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'salmon': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'scallop': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'shrimp': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'tilapia': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'tuna': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'turkey': ['beef', 'lamb', 'veal', 'pork', 'sausage', 'bacon', 'ham', 'bison', 'venison', 'steak'],
 'wheat bread': ['canadian white', 'ciabatta', 'cuban bread', 'dampfnudel', 'hardebrood', 'mollette', 'milk loaf', 'milk bread', 'milk roll', 'pane ticinese', 'piadina', 'shoti', 'texas toast', 'zopf'],
 'whole grain bread': ['canadian white', 'ciabatta', 'cuban bread', 'dampfnudel', 'hardebrood', 'mollette', 'milk loaf', 'milk bread', 'milk roll', 'pane ticinese', 'piadina', 'shoti', 'texas toast', 'zopf'],
 'whole wheat bread': ['canadian white', 'ciabatta', 'cuban bread', 'dampfnudel', 'hardebrood', 'mollette', 'milk loaf', 'milk bread', 'milk roll', 'pane ticinese', 'piadina', 'shoti', 'texas toast', 'zopf']}

SUB["japan"] = {'arborio rice': ['sushi rice'],
 'basmati': ['sushi rice'],
 'biangbiang noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'black rice': ['sushi rice'],
 'brown rice': ['sushi rice'],
 'cellophane noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'chinkiang pot cover noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'cumian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'cup noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'daoxiao noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'dragon beard noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fettucine': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fideo': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'fried noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'frozen noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'henan braised noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'hot dry noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'instant noodle': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'jasmine rice': ['sushi rice'],
 'jook-sing noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'kaomianjin': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lai fun': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lamian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'lasagne': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'liangpi': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'macaroni': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'matta rice': ['sushi rice'],
 'migan': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'misua': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mixian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mohnnudel': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'mung bean sheets': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'oil noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'paomo': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'parboiled rice': ['sushi rice'],
 'penne': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'ravioli': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rice': ['sushi rice'],
 'rice noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rice vermicelli': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'rigatoni': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'saang mein': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'schupfnudel': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'shahe fen': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'shrimp roe noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'silver needle noodles': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'spaghetti': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'white rice': ['sushi rice'],
 'wild rice': ['sushi rice'],
 'yi mein': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba'],
 'youmian': ['udon', 'hiyamugi', 'ramen', 'sanuki udon', 'shirataki noodles', 'soba', 'sōmen', 'uanko soba', 'yakisoba']}

SUB["mexico"] = {}

